/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package app.nourtabib.financialdatastreamingapp.avros;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountOutcomeContext extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9087271129593915179L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountOutcomeContext\",\"namespace\":\"app.nourtabib.financialdatastreamingapp.avros\",\"fields\":[{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"transactionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"nameDest\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<AccountOutcomeContext> ENCODER =
      new BinaryMessageEncoder<AccountOutcomeContext>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountOutcomeContext> DECODER =
      new BinaryMessageDecoder<AccountOutcomeContext>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountOutcomeContext> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountOutcomeContext> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountOutcomeContext> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AccountOutcomeContext>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountOutcomeContext to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountOutcomeContext from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountOutcomeContext instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountOutcomeContext fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public double amount;
  @Deprecated public java.lang.String transactionId;
  @Deprecated public java.time.Instant timestamp;
  @Deprecated public java.lang.String type;
  @Deprecated public java.lang.String nameDest;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountOutcomeContext() {}

  /**
   * All-args constructor.
   * @param amount The new value for amount
   * @param transactionId The new value for transactionId
   * @param timestamp The new value for timestamp
   * @param type The new value for type
   * @param nameDest The new value for nameDest
   */
  public AccountOutcomeContext(java.lang.Double amount, java.lang.String transactionId, java.time.Instant timestamp, java.lang.String type, java.lang.String nameDest) {
    this.amount = amount;
    this.transactionId = transactionId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.type = type;
    this.nameDest = nameDest;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return amount;
    case 1: return transactionId;
    case 2: return timestamp;
    case 3: return type;
    case 4: return nameDest;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: amount = (java.lang.Double)value$; break;
    case 1: transactionId = value$ != null ? value$.toString() : null; break;
    case 2: timestamp = (java.time.Instant)value$; break;
    case 3: type = value$ != null ? value$.toString() : null; break;
    case 4: nameDest = value$ != null ? value$.toString() : null; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public java.lang.String getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'nameDest' field.
   * @return The value of the 'nameDest' field.
   */
  public java.lang.String getNameDest() {
    return nameDest;
  }


  /**
   * Sets the value of the 'nameDest' field.
   * @param value the value to set.
   */
  public void setNameDest(java.lang.String value) {
    this.nameDest = value;
  }

  /**
   * Creates a new AccountOutcomeContext RecordBuilder.
   * @return A new AccountOutcomeContext RecordBuilder
   */
  public static app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder newBuilder() {
    return new app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder();
  }

  /**
   * Creates a new AccountOutcomeContext RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountOutcomeContext RecordBuilder
   */
  public static app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder newBuilder(app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder other) {
    if (other == null) {
      return new app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder();
    } else {
      return new app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder(other);
    }
  }

  /**
   * Creates a new AccountOutcomeContext RecordBuilder by copying an existing AccountOutcomeContext instance.
   * @param other The existing instance to copy.
   * @return A new AccountOutcomeContext RecordBuilder
   */
  public static app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder newBuilder(app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext other) {
    if (other == null) {
      return new app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder();
    } else {
      return new app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountOutcomeContext instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountOutcomeContext>
    implements org.apache.avro.data.RecordBuilder<AccountOutcomeContext> {

    private double amount;
    private java.lang.String transactionId;
    private java.time.Instant timestamp;
    private java.lang.String type;
    private java.lang.String nameDest;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[1].schema(), other.transactionId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.nameDest)) {
        this.nameDest = data().deepCopy(fields()[4].schema(), other.nameDest);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountOutcomeContext instance
     * @param other The existing instance to copy.
     */
    private Builder(app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[1].schema(), other.transactionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.nameDest)) {
        this.nameDest = data().deepCopy(fields()[4].schema(), other.nameDest);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder setAmount(double value) {
      validate(fields()[0], value);
      this.amount = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder clearAmount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder setTransactionId(java.lang.String value) {
      validate(fields()[1], value);
      this.transactionId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder clearTransactionId() {
      transactionId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[2], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder clearTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder setType(java.lang.String value) {
      validate(fields()[3], value);
      this.type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder clearType() {
      type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'nameDest' field.
      * @return The value.
      */
    public java.lang.String getNameDest() {
      return nameDest;
    }


    /**
      * Sets the value of the 'nameDest' field.
      * @param value The value of 'nameDest'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder setNameDest(java.lang.String value) {
      validate(fields()[4], value);
      this.nameDest = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'nameDest' field has been set.
      * @return True if the 'nameDest' field has been set, false otherwise.
      */
    public boolean hasNameDest() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'nameDest' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.AccountOutcomeContext.Builder clearNameDest() {
      nameDest = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountOutcomeContext build() {
      try {
        AccountOutcomeContext record = new AccountOutcomeContext();
        record.amount = fieldSetFlags()[0] ? this.amount : (java.lang.Double) defaultValue(fields()[0]);
        record.transactionId = fieldSetFlags()[1] ? this.transactionId : (java.lang.String) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.time.Instant) defaultValue(fields()[2]);
        record.type = fieldSetFlags()[3] ? this.type : (java.lang.String) defaultValue(fields()[3]);
        record.nameDest = fieldSetFlags()[4] ? this.nameDest : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountOutcomeContext>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountOutcomeContext>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountOutcomeContext>
    READER$ = (org.apache.avro.io.DatumReader<AccountOutcomeContext>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










