/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package app.nourtabib.financialdatastreamingapp.avros;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RawTransactionAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2648544004544175985L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RawTransactionAvro\",\"namespace\":\"app.nourtabib.financialdatastreamingapp.avros\",\"fields\":[{\"name\":\"transactionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"nameOrig\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"oldBalanceOrg\",\"type\":\"double\"},{\"name\":\"newBalanceOrig\",\"type\":\"double\"},{\"name\":\"nameDest\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"oldBalanceDest\",\"type\":\"double\"},{\"name\":\"newBalanceDest\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<RawTransactionAvro> ENCODER =
      new BinaryMessageEncoder<RawTransactionAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RawTransactionAvro> DECODER =
      new BinaryMessageDecoder<RawTransactionAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RawTransactionAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RawTransactionAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RawTransactionAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RawTransactionAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RawTransactionAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RawTransactionAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RawTransactionAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RawTransactionAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String transactionId;
  @Deprecated public java.time.Instant timestamp;
  @Deprecated public java.lang.String type;
  @Deprecated public double amount;
  @Deprecated public java.lang.String nameOrig;
  @Deprecated public double oldBalanceOrg;
  @Deprecated public double newBalanceOrig;
  @Deprecated public java.lang.String nameDest;
  @Deprecated public double oldBalanceDest;
  @Deprecated public double newBalanceDest;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RawTransactionAvro() {}

  /**
   * All-args constructor.
   * @param transactionId The new value for transactionId
   * @param timestamp The new value for timestamp
   * @param type The new value for type
   * @param amount The new value for amount
   * @param nameOrig The new value for nameOrig
   * @param oldBalanceOrg The new value for oldBalanceOrg
   * @param newBalanceOrig The new value for newBalanceOrig
   * @param nameDest The new value for nameDest
   * @param oldBalanceDest The new value for oldBalanceDest
   * @param newBalanceDest The new value for newBalanceDest
   */
  public RawTransactionAvro(java.lang.String transactionId, java.time.Instant timestamp, java.lang.String type, java.lang.Double amount, java.lang.String nameOrig, java.lang.Double oldBalanceOrg, java.lang.Double newBalanceOrig, java.lang.String nameDest, java.lang.Double oldBalanceDest, java.lang.Double newBalanceDest) {
    this.transactionId = transactionId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.type = type;
    this.amount = amount;
    this.nameOrig = nameOrig;
    this.oldBalanceOrg = oldBalanceOrg;
    this.newBalanceOrig = newBalanceOrig;
    this.nameDest = nameDest;
    this.oldBalanceDest = oldBalanceDest;
    this.newBalanceDest = newBalanceDest;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionId;
    case 1: return timestamp;
    case 2: return type;
    case 3: return amount;
    case 4: return nameOrig;
    case 5: return oldBalanceOrg;
    case 6: return newBalanceOrig;
    case 7: return nameDest;
    case 8: return oldBalanceDest;
    case 9: return newBalanceDest;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionId = value$ != null ? value$.toString() : null; break;
    case 1: timestamp = (java.time.Instant)value$; break;
    case 2: type = value$ != null ? value$.toString() : null; break;
    case 3: amount = (java.lang.Double)value$; break;
    case 4: nameOrig = value$ != null ? value$.toString() : null; break;
    case 5: oldBalanceOrg = (java.lang.Double)value$; break;
    case 6: newBalanceOrig = (java.lang.Double)value$; break;
    case 7: nameDest = value$ != null ? value$.toString() : null; break;
    case 8: oldBalanceDest = (java.lang.Double)value$; break;
    case 9: newBalanceDest = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public java.lang.String getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'nameOrig' field.
   * @return The value of the 'nameOrig' field.
   */
  public java.lang.String getNameOrig() {
    return nameOrig;
  }


  /**
   * Sets the value of the 'nameOrig' field.
   * @param value the value to set.
   */
  public void setNameOrig(java.lang.String value) {
    this.nameOrig = value;
  }

  /**
   * Gets the value of the 'oldBalanceOrg' field.
   * @return The value of the 'oldBalanceOrg' field.
   */
  public double getOldBalanceOrg() {
    return oldBalanceOrg;
  }


  /**
   * Sets the value of the 'oldBalanceOrg' field.
   * @param value the value to set.
   */
  public void setOldBalanceOrg(double value) {
    this.oldBalanceOrg = value;
  }

  /**
   * Gets the value of the 'newBalanceOrig' field.
   * @return The value of the 'newBalanceOrig' field.
   */
  public double getNewBalanceOrig() {
    return newBalanceOrig;
  }


  /**
   * Sets the value of the 'newBalanceOrig' field.
   * @param value the value to set.
   */
  public void setNewBalanceOrig(double value) {
    this.newBalanceOrig = value;
  }

  /**
   * Gets the value of the 'nameDest' field.
   * @return The value of the 'nameDest' field.
   */
  public java.lang.String getNameDest() {
    return nameDest;
  }


  /**
   * Sets the value of the 'nameDest' field.
   * @param value the value to set.
   */
  public void setNameDest(java.lang.String value) {
    this.nameDest = value;
  }

  /**
   * Gets the value of the 'oldBalanceDest' field.
   * @return The value of the 'oldBalanceDest' field.
   */
  public double getOldBalanceDest() {
    return oldBalanceDest;
  }


  /**
   * Sets the value of the 'oldBalanceDest' field.
   * @param value the value to set.
   */
  public void setOldBalanceDest(double value) {
    this.oldBalanceDest = value;
  }

  /**
   * Gets the value of the 'newBalanceDest' field.
   * @return The value of the 'newBalanceDest' field.
   */
  public double getNewBalanceDest() {
    return newBalanceDest;
  }


  /**
   * Sets the value of the 'newBalanceDest' field.
   * @param value the value to set.
   */
  public void setNewBalanceDest(double value) {
    this.newBalanceDest = value;
  }

  /**
   * Creates a new RawTransactionAvro RecordBuilder.
   * @return A new RawTransactionAvro RecordBuilder
   */
  public static app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder newBuilder() {
    return new app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder();
  }

  /**
   * Creates a new RawTransactionAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RawTransactionAvro RecordBuilder
   */
  public static app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder newBuilder(app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder other) {
    if (other == null) {
      return new app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder();
    } else {
      return new app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder(other);
    }
  }

  /**
   * Creates a new RawTransactionAvro RecordBuilder by copying an existing RawTransactionAvro instance.
   * @param other The existing instance to copy.
   * @return A new RawTransactionAvro RecordBuilder
   */
  public static app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder newBuilder(app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro other) {
    if (other == null) {
      return new app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder();
    } else {
      return new app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for RawTransactionAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RawTransactionAvro>
    implements org.apache.avro.data.RecordBuilder<RawTransactionAvro> {

    private java.lang.String transactionId;
    private java.time.Instant timestamp;
    private java.lang.String type;
    private double amount;
    private java.lang.String nameOrig;
    private double oldBalanceOrg;
    private double newBalanceOrig;
    private java.lang.String nameDest;
    private double oldBalanceDest;
    private double newBalanceDest;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.nameOrig)) {
        this.nameOrig = data().deepCopy(fields()[4].schema(), other.nameOrig);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.oldBalanceOrg)) {
        this.oldBalanceOrg = data().deepCopy(fields()[5].schema(), other.oldBalanceOrg);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.newBalanceOrig)) {
        this.newBalanceOrig = data().deepCopy(fields()[6].schema(), other.newBalanceOrig);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.nameDest)) {
        this.nameDest = data().deepCopy(fields()[7].schema(), other.nameDest);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.oldBalanceDest)) {
        this.oldBalanceDest = data().deepCopy(fields()[8].schema(), other.oldBalanceDest);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.newBalanceDest)) {
        this.newBalanceDest = data().deepCopy(fields()[9].schema(), other.newBalanceDest);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing RawTransactionAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.nameOrig)) {
        this.nameOrig = data().deepCopy(fields()[4].schema(), other.nameOrig);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.oldBalanceOrg)) {
        this.oldBalanceOrg = data().deepCopy(fields()[5].schema(), other.oldBalanceOrg);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.newBalanceOrig)) {
        this.newBalanceOrig = data().deepCopy(fields()[6].schema(), other.newBalanceOrig);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.nameDest)) {
        this.nameDest = data().deepCopy(fields()[7].schema(), other.nameDest);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.oldBalanceDest)) {
        this.oldBalanceDest = data().deepCopy(fields()[8].schema(), other.oldBalanceDest);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.newBalanceDest)) {
        this.newBalanceDest = data().deepCopy(fields()[9].schema(), other.newBalanceDest);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setTransactionId(java.lang.String value) {
      validate(fields()[0], value);
      this.transactionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearTransactionId() {
      transactionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[1], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setType(java.lang.String value) {
      validate(fields()[2], value);
      this.type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearType() {
      type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setAmount(double value) {
      validate(fields()[3], value);
      this.amount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearAmount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'nameOrig' field.
      * @return The value.
      */
    public java.lang.String getNameOrig() {
      return nameOrig;
    }


    /**
      * Sets the value of the 'nameOrig' field.
      * @param value The value of 'nameOrig'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setNameOrig(java.lang.String value) {
      validate(fields()[4], value);
      this.nameOrig = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'nameOrig' field has been set.
      * @return True if the 'nameOrig' field has been set, false otherwise.
      */
    public boolean hasNameOrig() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'nameOrig' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearNameOrig() {
      nameOrig = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'oldBalanceOrg' field.
      * @return The value.
      */
    public double getOldBalanceOrg() {
      return oldBalanceOrg;
    }


    /**
      * Sets the value of the 'oldBalanceOrg' field.
      * @param value The value of 'oldBalanceOrg'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setOldBalanceOrg(double value) {
      validate(fields()[5], value);
      this.oldBalanceOrg = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'oldBalanceOrg' field has been set.
      * @return True if the 'oldBalanceOrg' field has been set, false otherwise.
      */
    public boolean hasOldBalanceOrg() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'oldBalanceOrg' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearOldBalanceOrg() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'newBalanceOrig' field.
      * @return The value.
      */
    public double getNewBalanceOrig() {
      return newBalanceOrig;
    }


    /**
      * Sets the value of the 'newBalanceOrig' field.
      * @param value The value of 'newBalanceOrig'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setNewBalanceOrig(double value) {
      validate(fields()[6], value);
      this.newBalanceOrig = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'newBalanceOrig' field has been set.
      * @return True if the 'newBalanceOrig' field has been set, false otherwise.
      */
    public boolean hasNewBalanceOrig() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'newBalanceOrig' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearNewBalanceOrig() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'nameDest' field.
      * @return The value.
      */
    public java.lang.String getNameDest() {
      return nameDest;
    }


    /**
      * Sets the value of the 'nameDest' field.
      * @param value The value of 'nameDest'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setNameDest(java.lang.String value) {
      validate(fields()[7], value);
      this.nameDest = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'nameDest' field has been set.
      * @return True if the 'nameDest' field has been set, false otherwise.
      */
    public boolean hasNameDest() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'nameDest' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearNameDest() {
      nameDest = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'oldBalanceDest' field.
      * @return The value.
      */
    public double getOldBalanceDest() {
      return oldBalanceDest;
    }


    /**
      * Sets the value of the 'oldBalanceDest' field.
      * @param value The value of 'oldBalanceDest'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setOldBalanceDest(double value) {
      validate(fields()[8], value);
      this.oldBalanceDest = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'oldBalanceDest' field has been set.
      * @return True if the 'oldBalanceDest' field has been set, false otherwise.
      */
    public boolean hasOldBalanceDest() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'oldBalanceDest' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearOldBalanceDest() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'newBalanceDest' field.
      * @return The value.
      */
    public double getNewBalanceDest() {
      return newBalanceDest;
    }


    /**
      * Sets the value of the 'newBalanceDest' field.
      * @param value The value of 'newBalanceDest'.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder setNewBalanceDest(double value) {
      validate(fields()[9], value);
      this.newBalanceDest = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'newBalanceDest' field has been set.
      * @return True if the 'newBalanceDest' field has been set, false otherwise.
      */
    public boolean hasNewBalanceDest() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'newBalanceDest' field.
      * @return This builder.
      */
    public app.nourtabib.financialdatastreamingapp.avros.RawTransactionAvro.Builder clearNewBalanceDest() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RawTransactionAvro build() {
      try {
        RawTransactionAvro record = new RawTransactionAvro();
        record.transactionId = fieldSetFlags()[0] ? this.transactionId : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.time.Instant) defaultValue(fields()[1]);
        record.type = fieldSetFlags()[2] ? this.type : (java.lang.String) defaultValue(fields()[2]);
        record.amount = fieldSetFlags()[3] ? this.amount : (java.lang.Double) defaultValue(fields()[3]);
        record.nameOrig = fieldSetFlags()[4] ? this.nameOrig : (java.lang.String) defaultValue(fields()[4]);
        record.oldBalanceOrg = fieldSetFlags()[5] ? this.oldBalanceOrg : (java.lang.Double) defaultValue(fields()[5]);
        record.newBalanceOrig = fieldSetFlags()[6] ? this.newBalanceOrig : (java.lang.Double) defaultValue(fields()[6]);
        record.nameDest = fieldSetFlags()[7] ? this.nameDest : (java.lang.String) defaultValue(fields()[7]);
        record.oldBalanceDest = fieldSetFlags()[8] ? this.oldBalanceDest : (java.lang.Double) defaultValue(fields()[8]);
        record.newBalanceDest = fieldSetFlags()[9] ? this.newBalanceDest : (java.lang.Double) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RawTransactionAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<RawTransactionAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RawTransactionAvro>
    READER$ = (org.apache.avro.io.DatumReader<RawTransactionAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










